[package]
name = "netlink-packet-ipvs"
version = "0.0.1"
authors = ["David <davidventura27@gmail.com>"]
edition = "2018"
homepage = "https://github.com/davidventura/netlink-packet-ipvs"
repository = "https://github.com/davidventura/netlink-packet-ipvs"
keywords = ["netlink", "linux", "ipvs"]
license = "MIT"
readme = "README.md"
description = "generic netlink IPVS packet types"

[dependencies]
anyhow = "1.0.39"
byteorder = "1.4.2"
netlink-packet-core = { version = "0.7.0" }
netlink-packet-generic = "0.3.3"
netlink-packet-utils = { version = "0.5.2" }

[dev-dependencies]
netlink-sys = { version = "0.8.3" }
